---
title: "Springboard Final R Code"
author: "RJ"
date: "August 5, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=TRUE, eval=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Capstone Project - Maritime Data Intelligence System - Earnings Prediction, R code

### Data Wrangling
```{r,warning=FALSE,message=FALSE,eval=FALSE}
# Load all the packages used in the analysis
library("tidyverse")
library("lubridate")
library("caTools")
library("geosphere")
library("randomForest")
library("miscTools")

# Read the files
V_Fact_VoyPNL_File <- "F:\\Git\\capstone project\\dataSets\\V_Fact_VoyPNL.csv"
test_File <- "F:\\Git\\capstone project\\dataSets\\test.csv"
V_Dim_CargoAndGrade_File <- "F:\\Git\\capstone project\\dataSets\\V_Dim_CargoAndGrade.csv"
V_Dim_Vessel_File <- "F:\\Git\\capstone project\\dataSets\\V_Dim_Vessel.csv"
V_Dim_Voyage_File <- "F:\\Git\\capstone project\\dataSets\\V_Dim_Voyage.csv"
V_Dim_Ports_File <- "F:\\Git\\capstone project\\dataSets\\V_Dim_Ports.csv"
V_Fact_Vsched_File <- "F:\\Git\\capstone project\\dataSets\\V_Fact_VesselItinerary_Vsched.csv"
V_Dim_Cargo_File <- "F:\\Git\\capstone project\\dataSets\\V_Dim_Cargo.csv"

# Store the data into dataframe and check for blanks and NA
V_Fact_VoyPNL <- read.csv(V_Fact_VoyPNL_File, na.strings=c("","NA"), 
                          stringsAsFactors = FALSE)
test <- read.csv(test_File, na.strings=c("","NA"), stringsAsFactors = FALSE)
V_Dim_CargoAndGrade <- read.csv(V_Dim_CargoAndGrade_File, na.strings=c("","NA"),
                                stringsAsFactors = FALSE)
V_Dim_Vessel <- read.csv(V_Dim_Vessel_File, na.strings=c("","NA"), 
                         stringsAsFactors = FALSE)
V_Dim_Voyage <- read.csv(V_Dim_Voyage_File, na.strings=c("","NA"),
                         stringsAsFactors = FALSE)
V_Dim_Ports <- read.csv(V_Dim_Ports_File, na.strings=c("","NA"), 
                        stringsAsFactors = FALSE)
V_Fact_Vsched <- read.csv(V_Fact_Vsched_File, na.strings=c("","NA"), 
                          stringsAsFactors = FALSE)
V_Dim_Cargo <- read.csv(V_Dim_Cargo_File, na.strings=c("","NA"),
                        stringsAsFactors = FALSE)

```


```{r,warning=FALSE,message=FALSE,eval=FALSE}
#Look at the structure of the dataset
glimpse(V_Fact_VoyPNL)
glimpse(test)
glimpse(V_Dim_CargoAndGrade)
glimpse(V_Dim_Vessel)
glimpse(V_Dim_Voyage)
glimpse(V_Dim_Ports)
glimpse(V_Dim_Vsched)
glimpse(V_Dim_Cargo)
```

```{r,warning=FALSE,message=FALSE,eval=FALSE}
#Data Preparation - Voyage Data
#Find out vsl type, duration of voyages, when were they undertaken
#Distance covered during the voyage,Type of cargo

dfVoy <- V_Dim_Voyage %>% select(Dim_Voyage_Id, Vsl_Code, voyNum, 
                                 Fkey_Dim_Vessel_Id, VesselName,
                                 PortOfFirstLoad_PortName,
                                 PortOfLastDischarge_Portname,
                                 Fkey_Dim_Cargo_id,CommenceGMT, CompleteGMT)

#Filter for ports with no names and cargo IDs as -1

dfVoy <- dfVoy %>% filter(PortOfFirstLoad_PortName!='--') %>%
  filter(PortOfLastDischarge_Portname!='--') %>% filter(Fkey_Dim_Cargo_id!=-1)

#Calcultae the voyage duration

dfVoy$Duration <- round(difftime(dfVoy$CompleteGMT,dfVoy$CommenceGMT, units='days'),2)

#Month in which the voyage starts

dfVoy$Month <- month(dfVoy$CommenceGMT, label = TRUE)

#Year in which the voyage starts
dfVoy$Year <- year(dfVoy$CommenceGMT, label = TRUE)

#add areas for the first load port and last discharge port.
dfVoy$LoadArea <- V_Dim_Ports$Area[match(dfVoy$PortOfFirstLoad_PortName,
                                         V_Dim_Ports$PortName)]
dfVoy$DischargeArea <- V_Dim_Ports$Area[match(dfVoy$PortOfLastDischarge_Portname,
                                              V_Dim_Ports$PortName)]

#calculate the distance travelled
#Add lat long of ports

dfVoy$CommenceLat <- V_Dim_Ports$Latitude[match(dfVoy$PortOfFirstLoad_PortName,
                                                V_Dim_Ports$PortName)]
dfVoy$CommenceLon <- V_Dim_Ports$Longitude[match(dfVoy$PortOfFirstLoad_PortName,
                                                 V_Dim_Ports$PortName)]
dfVoy$CompleteLat <- V_Dim_Ports$Latitude[match(dfVoy$PortOfLastDischarge_Portname,
                                                V_Dim_Ports$PortName)]
dfVoy$CompleteLon <- V_Dim_Ports$Longitude[match(dfVoy$PortOfLastDischarge_Portname,
                                                 V_Dim_Ports$PortName)]

start <- cbind(dfVoy$CommenceLon,dfVoy$CommenceLat)
stop <- cbind(dfVoy$CompleteLon,dfVoy$CompleteLat)

#To get the distance in Nautical Miles
dfVoy$Distance <- round(distm(start,stop, fun=distHaversine)[,1]/1852,2) 

rm(start,stop) #remove

#remove not required columns
dfVoy <- dfVoy %>% select(-starts_with("C")) %>% select(-starts_with("P"))

#get info on cargo
dfVoy$CargoGradeID <- V_Dim_Cargo$Fkey_Dim_CargoAndGrade_ID[match
                                                            (dfVoy$Dim_Voyage_Id,           
                                                              V_Dim_Cargo$Fkey_Dim_Voyage_Id)]
dfVoy$Cargo <- V_Dim_CargoAndGrade$CargoGrade_txt[match
                                                  (dfVoy$CargoGradeID,
                                                  V_Dim_CargoAndGrade$Dim_CargoAndGrade_Id)]

#Clean up
dfVoy <- dfVoy %>% select(-Fkey_Dim_Cargo_id, -CargoGradeID)

#Get the cargo Qty
dfVoy$Qty <- V_Fact_VoyPNL$Cargo_Lift_Act[match(dfVoy$Dim_Voyage_Id,
                                                V_Fact_VoyPNL$Fkey_Dim_Voyage_Id)]

#Remove na values
dfVoy <- dfVoy %>% filter(!is.na(Qty))

#Get Vessel Details
dfVoy$VesselType <- V_Dim_Vessel$VesselType[match(dfVoy$Fkey_Dim_Vessel_Id, 
                                                  V_Dim_Vessel$Dim_Vessel_Id)]

dfVoy$Dwt <- V_Dim_Vessel$dwt[match(dfVoy$Fkey_Dim_Vessel_Id,
                                    V_Dim_Vessel$Dim_Vessel_Id)]

#Remove na values
dfVoy <- dfVoy %>% filter(!is.na(Dwt))

#Get earnings
dfVoy$TCE <- V_Fact_VoyPNL$tcEquv_Act[match(dfVoy$Dim_Voyage_Id,
                                            V_Fact_VoyPNL$Fkey_Dim_Voyage_Id)]
dfVoy$Earnings <- dfVoy$Duration * dfVoy$TCE
```

```{r, warning=FALSE, eval=FALSE, message=FALSE}
#Final Table for predictions
Final <- dfVoy %>% select(-Dim_Voyage_Id:-VesselName)
Final$Duration <- as.numeric(Final$Duration)
Final$Earnings <- as.numeric(Final$Earnings)
#Convert all char to factor
Final <- Final %>% mutate_if(is.character, as.factor)

#remove NA rows
Final <- Final[complete.cases(Final),]

```

### Preliminary Exploration

```{r,warning=FALSE,message=FALSE, eval=FALSE}
# Calculate average earnings for each year for each vessel type
avgv2 <- aggregate(Final[,c("Earnings")],list(Year=Final$Year,
                                              VesselType=Final$VesselType), 
                   mean)
head(avgv2)

# plot average of earnings from 2009 to 2019 for each vessel type
avgv2yr <- avgv2[avgv2$Year <= 2019 & avgv2$Year >= 2009,]

ggplot(avgv2yr, aes(x=VesselType,y=x)) +
  geom_bar(aes(fill = factor(VesselType)),stat="identity")+
  facet_wrap(~Year, ncol = 2, nrow = 5) +
  theme(axis.text.x = element_text(angle=45,hjust = 1), 
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Average earnings vs Vessel type", x = "Vessel type",
       y = "Average earnings(USD)") +
  guides(fill=guide_legend(title = "Vessel Type"))   
```

```{r,warning=FALSE,message=FALSE, eval=FALSE}
#calculate average earnings for each vessel type for all years
avgv3 <- aggregate(Final[,c("Earnings")],list(VesselType=Final$VesselType), mean)

# plot average for each vessel type for all years
ggplot(avgv3, aes(x=VesselType,y=x)) +
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle=45,hjust = 1), 
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Average earnings vs Vessel type", x = "Vessel type",
       y = "Average earnings(USD)") 
```

```{r,warning=FALSE,message=FALSE, eval=FALSE}
# 1. sum of earnings for each year for each vessel type
sumv2 <- aggregate(Final[,c("Earnings")],list(Year=Final$Year,
                                              VesselType=Final$VesselType), sum)

# plot average of each year for each type of vessel
sumv2yr <- sumv2[sumv2$Year <= 2019 & sumv2$Year >= 2009,]

ggplot(sumv2yr, aes(x=VesselType,y=x)) +
  geom_bar(aes(fill = factor(VesselType)),stat="identity")+
  facet_wrap(~Year, ncol = 2, nrow = 5) +
  theme(axis.text.x = element_text(angle=45,hjust = 1),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Sum of earnings vs Vessel type", x = "Vessel type",
       y = "Sum of earnings(USD)") +
  guides(fill=guide_legend(title = "Vessel Type"))  
```


```{r,warning=FALSE,message=FALSE, eval=FALSE}
#Sum of earnings for each Cargo type
sumv6 <- aggregate(Final[,c("Earnings")],list(cargo_type=Final$Cargo), sum)
sumv6 <- sumv6[order(-sumv6$x),]

#plot sum of earnings for each cargo type
ggplot(sumv6, aes(x=reorder(cargo_type,-x),y=x)) +
  geom_bar(stat="identity",position = "dodge")+
  theme(axis.text.x = element_text(angle=45,hjust = 1), 
        plot.title = element_text(hjust = 0.5)) +  
  labs(title = "Sum of earnings vs Cargo type", x = "Cargo type", 
       y = "Sum of earnings(USD)") 
```

```{r,warning=FALSE,message=FALSE, eval=FALSE}
#Calculate average monthly earnings for each month
avgv6 <- aggregate(Final[,c("Earnings")],list(Month=Final$Month), mean)

#plot average monthly earnings for each month
ggplot(avgv6, aes(x=sort(Month),y=x)) +
  geom_bar(stat="identity",position = "dodge")+
  theme(axis.text.x = element_text(angle=45,hjust = 1), 
        plot.title = element_text(hjust = 0.5)) +  
  labs(title = "Average earnings vs Month", x = "Month", 
       y = "Average earnings(USD)") 

# Boxplot to find seasonality in the business.
ggplot(Final, aes(x=Month, y=Earnings)) +
    geom_boxplot()
```

## Machine Learning

### Linear Regression 

```{r,warning=FALSE,message=FALSE, eval=FALSE}
#Split the data into training dataset and testing dataset with a 70/30 ratio.
# set the seed to make the partition reproduciable.
set.seed(40)
split <- sample(nrow(Final), floor(0.7*nrow(Final)))
Final_train <- Final[split,]
Final_test <- Final[-split,]
```

```{r,warning=FALSE,message=FALSE, eval=FALSE}
#Check the rows for training and testing the datasets
nrow(Final_train)
nrow(Final_test)
```

### Model 1
```{r,warning=FALSE,message=FALSE, eval=FALSE}
# Model1 starts with fewer independent variables.
model1 <- lm(Earnings~VesselType + Duration, Final_train)

#Linear Regression Diagnostics
summary(model1) 
```

### Model 2
```{r,warning=FALSE,message=FALSE, eval=FALSE}
# Model 2 adding more independent variables.
model2 <- lm(Earnings~VesselType + Duration + Cargo + Qty, Final_train) 

#Linear Regression Diagnostics
summary(model2) 
```

### Model 3
```{r,warning=FALSE,message=FALSE, eval=FALSE}
# Model 3 adding more independent variables.
model3 <- lm(Earnings~VesselType + Duration + Cargo + Qty + Month +
            DischargeArea + Dwt, Final_train)

#Linear Regression Diagnostics
summary(model3) 
```

### Prediction of the earnings
```{r, warning=FALSE, eval=FALSE}
# Using model 3 to predict the test dataset.
prediction <- predict(model3, Final_test)

plot(prediction, Final_test$Earnings, xlim=c(0,25000))
```

### Model using random forest algorithm

```{r, warning=FALSE, eval=FALSE}
###########################################################################################
#Divide into training & test datasets
set.seed(666)
split <- sample(nrow(Final), floor(0.7*nrow(Final)))
train <- Final[split,]
test <- Final[-split,]

#Random Forest model
model <- randomForest(Earnings ~ Distance+Duration+Month+LoadArea+DischargeArea+Cargo+Qty
                      +VesselType+Dwt, 
                      data=train,
                      ntree=500,
                      mtry=4,
                      importance=TRUE,
                      na.action = na.roughfix,
                      replace=FALSE)

model

(r2 <- rSquared(test$Earnings, test$Earnings - predict(model, test)))
(mse <- mean((test$Earnings - predict(model, test))^2)) 

p <- ggplot(aes(x=actual, y=pred),
            data=data.frame(actual=test$Earnings, pred=predict(model, test)))
p + geom_point() +
  geom_abline(color="red") +
  ggtitle(paste("RandomForest Regression in R r^2=", r2, sep=""))

#Variable Importance
rn <- round(importance(model), 2)
rn[order(rn[,1], decreasing=TRUE),]

#Variale Importance Plot
varImpPlot(model, main="")
title(main="Variable Importance Random Forest")

#Plot the error rate
plot(model, main="")
title(main="Error Rate Random Forest")

```

### Remove outliers and apply Random Forest

### Model 1

```{r,warning=FALSE, eval=FALSE}
#remove outliers - Duration

x1 <- quantile(Final$Duration,c(0.01,0.99))
Final <- Final[Final$Duration >=x1[1] & Final$Duration<=x1[2],]

###########################################################################################
#Divide into training & test datasets
set.seed(666)
split <- sample(nrow(Final), floor(0.7*nrow(Final)))
train <- Final[split,]
test <- Final[-split,]

#Random Forest model
model1 <- randomForest(Earnings ~ Distance+Duration+Month+LoadArea+DischargeArea+Cargo+Qty
                      +VesselType+Dwt, 
                      data=train,
                      ntree=500,
                      mtry=4,
                      importance=TRUE,
                      na.action = na.roughfix,
                      replace=FALSE)

model1

(r21 <- rSquared(test$Earnings, test$Earnings - predict(model1, test)))
(mse1 <- mean((test$Earnings - predict(model1, test))^2)) 

p <- ggplot(aes(x=actual, y=pred),
            data=data.frame(actual=test$Earnings, pred=predict(model1, test)))
p + geom_point() +
  geom_abline(color="red") +
  ggtitle(paste("RandomForest Regression in R r^2=", r21, sep=""))

#Variable Importance
rn1 <- round(importance(model1), 2)
rn1[order(rn1[,1], decreasing=TRUE),]

#Variale Importance Plot
varImpPlot(model1, main="")
title(main="Variable Importance Random Forest")

#Plot the error rate
plot(model1, main="")
title(main="Error Rate Random Forest")


#Test it on the test dataset
outcome1 <- predict(model1, test)

```

### Model 2

```{r,warning=FALSE, eval=FALSE}
#remove outliers - Duration and Distance
x2 <- quantile(Final$Distance,c(0.01,0.99))
Final <- Final[Final$Distance >=x2[1] & Final$Distance<=x2[2],]
###########################################################################################
#Divide into training & test datasets
set.seed(666)
split <- sample(nrow(Final), floor(0.7*nrow(Final)))
train <- Final[split,]
test <- Final[-split,]

#Random Forest model
model2 <- randomForest(Earnings ~ Distance+Duration+Month+LoadArea+DischargeArea+Cargo+Qty
                      +VesselType+Dwt, 
                      data=train,
                      ntree=500,
                      mtry=4,
                      importance=TRUE,
                      na.action = na.roughfix,
                      replace=FALSE)

model2

(r22 <- rSquared(test$Earnings, test$Earnings - predict(model2, test)))
(mse2 <- mean((test$Earnings - predict(model2, test))^2)) 

p <- ggplot(aes(x=actual, y=pred),
            data=data.frame(actual=test$Earnings, pred=predict(model2, test)))
p + geom_point() +
  geom_abline(color="red") +
  ggtitle(paste("RandomForest Regression in R r^2=", r22, sep=""))

#Variable Importance
rn2 <- round(importance(model2), 2)
rn2[order(rn2[,1], decreasing=TRUE),]

#Variale Importance Plot
varImpPlot(model2, main="")
title(main="Variable Importance Random Forest")

#Plot the error rate
plot(model2, main="")
title(main="Error Rate Random Forest")


#Test it on the test dataset
outcome2 <- predict(model2, test)

```

### Model 3

```{r,warning=FALSE, eval=FALSE}
#remove outliers - Duration, Distance and Quantity
x3 <- quantile(Final$Qty,c(0.01,0.99))
Final <- Final[Final$Qty >=x3[1] & Final$Qty<=x3[2],]
###########################################################################################
#Divide into training & test datasets
set.seed(666)
split <- sample(nrow(Final), floor(0.7*nrow(Final)))
train <- Final[split,]
test <- Final[-split,]

#Random Forest model
model3 <- randomForest(Earnings ~ Distance+Duration+Month+LoadArea+DischargeArea+Cargo+Qty
                      +VesselType+Dwt, 
                      data=train,
                      ntree=500,
                      mtry=4,
                      importance=TRUE,
                      na.action = na.roughfix,
                      replace=FALSE)

model3

(r23 <- rSquared(test$Earnings, test$Earnings - predict(model3, test)))
(mse3 <- mean((test$Earnings - predict(model3, test))^2)) 

p <- ggplot(aes(x=actual, y=pred),
            data=data.frame(actual=test$Earnings, pred=predict(model3, test)))
p + geom_point() +
  geom_abline(color="red") +
  ggtitle(paste("RandomForest Regression in R r^2=", r23, sep=""))

#Variable Importance
rn3 <- round(importance(model3), 2)
rn3[order(rn3[,1], decreasing=TRUE),]

#Variale Importance Plot
varImpPlot(model3, main="")
title(main="Variable Importance Random Forest")

#Plot the error rate
plot(model3, main="")
title(main="Error Rate Random Forest")


#Test it on the test dataset
outcome3 <- predict(model3, test)

```

### Model 4

```{r,warning=FALSE, eval=FALSE}
#remove outliers - Duration, Distance, Quantity and Dwt
x4 <- quantile(Final$Dwt,c(0.01,0.99))
Final <- Final[Final$Dwt >=x4[1] & Final$Dwt<=x4[2],]

###########################################################################################
#Divide into training & test datasets
set.seed(666)
split <- sample(nrow(Final), floor(0.7*nrow(Final)))
train <- Final[split,]
test <- Final[-split,]

#Random Forest model
model4 <- randomForest(Earnings ~ Distance+Duration+Month+LoadArea+DischargeArea+Cargo+Qty
                      +VesselType+Dwt, 
                      data=train,
                      ntree=500,
                      mtry=4,
                      importance=TRUE,
                      na.action = na.roughfix,
                      replace=FALSE)

model4

(r24 <- rSquared(test$Earnings, test$Earnings - predict(model4, test)))
(mse4 <- mean((test$Earnings - predict(model4, test))^2)) 

p <- ggplot(aes(x=actual, y=pred),
            data=data.frame(actual=test$Earnings, pred=predict(model4, test)))
p + geom_point() +
  geom_abline(color="red") +
  ggtitle(paste("RandomForest Regression in R r^2=", r24, sep=""))

#Variable Importance
rn4 <- round(importance(model4), 2)
rn4[order(rn4[,1], decreasing=TRUE),]

#Variale Importance Plot
varImpPlot(model4, main="")
title(main="Variable Importance Random Forest")

#Plot the error rate
plot(model4, main="")
title(main="Error Rate Random Forest")


#Test it on the test dataset
outcome4 <- predict(model4, test)
```

### Model 5

```{r,warning=FALSE, eval=FALSE}
#remove outliers - Duration, Distance, Quantity, Dwt and Earnings
Final$Earnings <- as.numeric(Final$Earnings)
x5 <- quantile(Final$Earnings,c(0.01,0.99))
Final <- Final[Final$Earnings >=x5[1] & Final$Earnings<=x5[2],]

###########################################################################################
#Divide into training & test datasets
set.seed(666)
split <- sample(nrow(Final), floor(0.7*nrow(Final)))
train <- Final[split,]
test <- Final[-split,]

#Random Forest model
model5 <- randomForest(Earnings ~ Distance+Duration+Month+LoadArea+DischargeArea+Cargo+Qty
                      +VesselType+Dwt, 
                      data=train,
                      ntree=500,
                      mtry=4,
                      importance=TRUE,
                      na.action = na.roughfix,
                      replace=FALSE)

model5

(r25 <- rSquared(test$Earnings, test$Earnings - predict(model5, test)))
(mse5 <- mean((test$Earnings - predict(model5, test))^2)) 

p <- ggplot(aes(x=actual, y=pred),
            data=data.frame(actual=test$Earnings, pred=predict(model5, test)))
p + geom_point() +
  geom_abline(color="red") +
  ggtitle(paste("RandomForest Regression in R r^2=", r25, sep=""))

#Variable Importance
rn5 <- round(importance(model5), 2)
rn5[order(rn5[,1], decreasing=TRUE),]

#Variale Importance Plot
varImpPlot(model5, main="")
title(main="Variable Importance Random Forest")

#Plot the error rate
plot(model5, main="")
title(main="Error Rate Random Forest")


#Test it on the test dataset
outcome5 <- predict(model5, test)
```
